services:
  web:
    image: ghcr.io/zjx-artcc/new-website:master
    ports:
      - 3700:3700
    container_name: new-website
    restart: always
    environment:
      BODY_SIZE_LIMIT: "5e+7"
    volumes:
      - new-website:/usr/src/app/static/documents
  
volumes:
  new-website: