name: Deploy to test

on:
  push:
    branches: 'master'
  workflow_dispatch:

jobs:
  build_site:
    runs-on: self-hosted
    steps:
    - name: Setup
      uses: actions/checkout@v2
    - name: Deploy
      run: docker compose up --build -d
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CONNECT_URL: ${{ secrets.CONNECT_URL }}
      CONNECT_ID: ${{ secrets.CONNECT_ID }}
      CONNECT_SECRET: ${{ secrets.CONNECT_SECRET }}
      TOKEN_URL: ${{ secrets.TOKEN_URL }}
      USER_INFO_URL: ${{ secrets.USER_INFO_URL }}
      VATUSA_KEY: ${{ secrets.VATUSA_KEY }}