name: Deploy to test

on:
  push:
    branches: 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action
      with:
        images: ghcr.io/${{ github.repository }}
    - name: Build and push image
      uses: docker/build-push-action
      id: push
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CONNECT_URL: ${{ secrets.CONNECT_URL }}
      CONNECT_ID: ${{ secrets.CONNECT_ID }}
      CONNECT_SECRET: ${{ secrets.CONNECT_SECRET }}
      TOKEN_URL: ${{ secrets.TOKEN_URL }}
      USER_INFO_URL: ${{ secrets.USER_INFO_URL }}
      VATUSA_KEY: ${{ secrets.VATUSA_KEY }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}